name: 'Manual Build & Depoly'
on: workflow_dispatch
jobs:
  rest-info-lib:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the latest changes
        uses: actions/checkout@v4
      - name: setup java and maven
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: deploy to github-packages
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
